.TH FINDD 1 "December 17, 2012" "version 1.0"

.SH NAME
findd -- duplicates searching tool

.SH SYNOPSIS

findd --scan <DIRS> [--recursive] [--include-hidden] [--save <PATH>] [-NSC] [--remove]

findd --restore <PATH> [--save <PATH>] [-NSC] [--remove] 

.SH DESCRIPTION

.B Simple tool that help you searching duplicates on hard drive(s).

.SH OPTIONS

.TP 25	
--version, -v
Print what version you use.

.TP 25
--help, -h
Print the help message.

.TP 25
--scan <DIRS>, -s
Specify directories to scan separated by colon symbol (:). Ex : --scan /foo/bar:/bar/foo.

.TP 25
--recursive, -r
Scan recusively the directories you specified with --scan option.

.TP 25
--include-hidden
Include hidden files when you scan directories.

.TP 25
--restore <PATH>, -i
find duplicates from a file previously saved by the program.

.TP 25
--save <PATH>, -o
Store the result of the file list built from input parameters as xml. Use it to store a scan result.

.TP 25
--remove
Enable dialog to delete duplicates 

.TP 25
--compare-name, -N
search duplicates by name

.TP 25
--compare-size, -S
search duplicates by size

.TP 25
--compare-content, -C
search duplicates by content

.SH AUTHORS

Florian Mhun \<florian.mhun@gmail.com\>

Sara Ressam \<sara.ressam@gmail.com\>

Bastien Nouhant \<bastien.nouhant@gmail.com\>

Jerome Cornet \<jerome.cornet@gmail.com\>