.TH FINDD 1 "September 26, 2012" "version 1.0"

.SH NAME

findd -- Duplicates searching tool

.SH SYNOPSIS

.B findd [-NSC] [-i PATH] [-o PATH]

.SH DESCRIPTION

.B This tool is awesome.

.B The options are as follows:
.TP 30
-i PATH, --in-scan=PATH
Get files from saved scan to increase performances.

.TP 30
-o PATH, --out-scan=PATH.
Output scan into a file in order to use the -i option the next time you apply a duplicates searching on the PATH directory.

.TP 30
-s, --stats

.TP 30
-r, --recursive

.TP 30
-N, --compare-name

.TP 30
-S, --compare-size

.TP 30
-C, --compare-content

.TP 30
-h, --help

.TP 30
-v, --version

.SH AUTHORS

.B Florian Mhun \<florian.mhun at gmail.com\>

.B Sara Ressam \<sara.ressam at gmail.com\>

.B Bastien Nohant \<bastien.nohant at gmail.com\>
